package nonstaticvari;

import java.util.Scanner;

public class LunchMenu {

	static int total;
	public static void main(String[] args) {
		// TODO Autogenerated method stub
		Scanner sc = new Scanner(System.in);
		while (true) {
			System.out.println("---------------------------");
			System.out.println("1. Biryani");
			System.out.println("2. Drinks");
			System.out.println("3. Dessert");
			System.out.println("4. Bill");
			System.out.println("5. Exit");

			System.out.println("Please select 1 to 5 option");
			System.out.println("---------------------------");
			int i = sc.nextInt();

			switch (i) {
			case 1:
				BiryaniDetails biryani = new BiryaniDetails();
				biryani.biryaniPrice();
				break;
			case 2:
				DrinksDetails drinks = new DrinksDetails();
				drinks.drinkPrice();
				break;
			case 3:
				DessertDetails dessert = new DessertDetails();
				dessert.dessertPrice();
				break;
			case 4:
				System.out.println("Your total Bill is :$" + total);
				break;
			case 5:
				System.out.println("Your total Bill is :$" + total);
				System.out.println("Thank you! Enjoy your lunch!!!");
				System.exit(0);
				sc.close();
				break;
			default:
			System.out.println("Please choose between 1 to 5");
			System.out.println("----------------------------");
			}
		}
	}
}
